### ISSUE TITLE
The training procedure can not work on VLG 2.5.2

### ISSUE THREAD

**Issue by luofangcheng** [Be-bo/VisualGaitLab#10]
when I finish the labeling frames and click the  "save and quit" bottom, the “Label Frames” can't be closed.  And then, I click "X" to close the "Label Frames", the training procedure can't be active.

https://user-images.githubusercontent.com/112549604/187662483-58b1fa18-86f3-4fbc-ace9-44640f9b151f.mp4

**Comment by judgyknowitall** [comment]
It looks like it can't find the "tables" dependency. Please follow the steps [here](https://github.com/Be-bo/VisualGaitLab/wiki/Common-Errors#import-error-tables) to make sure it is installed. Just closing the labeling window will not save your work.

**Comment by luofangcheng** [comment]
Thanks, the issue was solved.
