### ISSUE TITLE
Dependency Installation of v2.5 stalls forever on fresh Windows 10 install.

### ISSUE THREAD

**Issue by gdevenyi** [Be-bo/VisualGaitLab#2]
I have a brand new Windows 10 install, setup exclusively for VisualGaitLab.

Dependency Installation of v2.5 hangs forever waiting.

Based on process info and the dates of files, it appears that the code has stopped at
https://github.com/Be-bo/VisualGaitLab/blob/master/MainWindow/DependencyInstallationMethods.cs#L97

Cancelling and dropping to the command line to interact with the installed conda, (the bundled Miniconda3 env), and attempting to run the command manually sits and waits forever.

The miniconda3 bunded is very old.

I have found that `conda update conda`, which updates the conda command to the latest version enables the `conda env create` to successfully solve the environment.

I suggest updating to v2.5.1 to bundle the latest Miniconda3 (or even better, Minimamba)

**Comment by judgyknowitall** [comment]
Thank you @gdevenyi for the suggestion! I will add this solution to the next update.

**Comment by judgyknowitall** [comment]
Solved (almost. see commit message) in v2.5.1 (commit [39b182a](https://github.com/Be-bo/VisualGaitLab/commit/39b182a6ff4254c406668dede9bdc45d29c1c45a))
